version: 2
jobs:
  build:
    working_directory: ~/spirit-island-scoring-app
    docker:
      - image: circleci/node:13.7.0
    steps:
      - checkout

      - run:
          name: update-yarn
          command: 'sudo yarn global add yarn@latest'

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}

      # run tests!
      - run: 
          name: test
          command: yarn test
   
      - run:
          name: code-coverage
          command: yarn test:coveralls